import { describe, expect, it } from 'vitest'
import { decodeRedLetterCues } from '../../src/reference/red-letter-cues'
import { makeVerseId } from '../../src/reference/verse-id'
import type { TaggedVerse } from '../../src/modules/verse-content'
import {
  deriveRedLetterCues,
  renderRedLetterCuesModule,
} from './derive-red-letter-cues'

const verse = (
  text: string,
  red?: { start: number; end: number }[],
): TaggedVerse => ({ text, tags: [], ...(red ? { red } : {}) })

const derive = (books: Record<number, Record<number, TaggedVerse>>) =>
  decodeRedLetterCues(deriveRedLetterCues(books))

describe('deriveRedLetterCues', () => {
  it('classifies a verse whose red spans cover every word as full', () => {
    const cues = derive({
      40: { [makeVerseId(40, 5, 4)]: verse('Blessed are they.', [{ start: 0, end: 17 }]) },
    })
    expect(cues.get(makeVerseId(40, 5, 4))).toEqual({ kind: 'full' })
  })

  it('treats uncovered punctuation and quotes as insignificant', () => {
    const cues = derive({
      42: {
        [makeVerseId(42, 24, 7)]: verse('“Rise again.”', [{ start: 0, end: 12 }]),
      },
    })
    expect(cues.get(makeVerseId(42, 24, 7))).toEqual({ kind: 'full' })
  })

  it('flags red at end when speech opens mid-verse and runs to the close', () => {
    const cues = derive({
      40: {
        [makeVerseId(40, 4, 7)]: verse('Jesus replied, “Do not test.”', [
          { start: 15, end: 29 },
        ]),
      },
    })
    expect(cues.get(makeVerseId(40, 4, 7))).toEqual({
      kind: 'partial',
      redAtStart: false,
      redAtEnd: true,
    })
  })

  it('flags red at start when speech ends mid-verse', () => {
    const cues = derive({
      41: {
        [makeVerseId(41, 1, 17)]: verse('“Follow Me,” Jesus said.', [
          { start: 0, end: 12 },
        ]),
      },
    })
    expect(cues.get(makeVerseId(41, 1, 17))).toEqual({
      kind: 'partial',
      redAtStart: true,
      redAtEnd: false,
    })
  })

  it('flags neither edge when the red span sits mid-verse', () => {
    const cues = derive({
      43: {
        [makeVerseId(43, 1, 38)]: verse('He asked, “What?” and they came.', [
          { start: 10, end: 17 },
        ]),
      },
    })
    expect(cues.get(makeVerseId(43, 1, 38))).toEqual({
      kind: 'partial',
      redAtStart: false,
      redAtEnd: false,
    })
  })

  it('flags both edges when red covers the edges but not the middle', () => {
    const cues = derive({
      43: {
        [makeVerseId(43, 4, 17)]: verse('“Go,” He said, “call him.”', [
          { start: 0, end: 5 },
          { start: 15, end: 26 },
        ]),
      },
    })
    expect(cues.get(makeVerseId(43, 4, 17))).toEqual({
      kind: 'partial',
      redAtStart: true,
      redAtEnd: true,
    })
  })

  it('omits verses without red spans', () => {
    const cues = derive({
      1: { [makeVerseId(1, 1, 1)]: verse('In the beginning.') },
      40: { [makeVerseId(40, 1, 1)]: verse('The genealogy.', []) },
    })
    expect(cues.size).toBe(0)
  })
})

describe('renderRedLetterCuesModule', () => {
  it('renders a TypeScript module that carries the encoded table', () => {
    const encoded = deriveRedLetterCues({
      40: { [makeVerseId(40, 5, 4)]: verse('Blessed.', [{ start: 0, end: 8 }]) },
    })
    const source = renderRedLetterCuesModule(encoded)
    expect(source).toContain('export const RED_LETTER_CUES =')
    expect(source).toContain(encoded)
    expect(source).toContain('Generated by')
  })
})
