import type { FormatSpan, StructuredVerse } from '../../src/modules/verse-content'
import {
  encodeRedLetterCues,
  type RedLetterCueCode,
} from '../../src/reference/red-letter-cues'
import type { BsbArtifact } from './build-bsb-artifact'

// Letters and digits decide coverage; whitespace, punctuation, and quote
// marks outside the red spans (e.g. a closing quote after Jesus' words in
// Luke 24:7) never demote a verse from full to partial.
const SIGNIFICANT = /[\p{L}\p{N}]/u

const isCovered = (spans: readonly FormatSpan[], index: number): boolean =>
  spans.some((span) => index >= span.start && index < span.end)

const cueCodeOf = (verse: StructuredVerse): RedLetterCueCode | null => {
  const spans = verse.red ?? []
  if (spans.length === 0) return null
  const significant: number[] = []
  for (let index = 0; index < verse.text.length; index++) {
    if (SIGNIFICANT.test(verse.text[index])) significant.push(index)
  }
  if (significant.length === 0) return null
  const uncovered = significant.some((index) => !isCovered(spans, index))
  if (!uncovered) return 'F'
  const redAtStart = isCovered(spans, significant[0])
  const redAtEnd = isCovered(spans, significant[significant.length - 1])
  if (redAtStart && redAtEnd) return 'B'
  if (redAtStart) return 'S'
  if (redAtEnd) return 'E'
  return 'M'
}

export const deriveRedLetterCues = (books: BsbArtifact['books']): string => {
  const entries: { verseId: number; code: RedLetterCueCode }[] = []
  for (const book of Object.values(books)) {
    for (const [verseId, verse] of Object.entries(book)) {
      const code = cueCodeOf(verse)
      if (code !== null) entries.push({ verseId: Number(verseId), code })
    }
  }
  return encodeRedLetterCues(entries)
}

const CHUNK_LENGTH = 74

export const renderRedLetterCuesModule = (encoded: string): string => {
  const chunks: string[] = []
  for (let at = 0; at < encoded.length; at += CHUNK_LENGTH) {
    chunks.push(`  '${encoded.slice(at, at + CHUNK_LENGTH)}'`)
  }
  const literal = chunks.length > 0 ? chunks.join(' +\n') : "  ''"
  return [
    '// Generated by scripts/build-bsb-module.mjs from the BSB source tables —',
    '// do not edit by hand.',
    'export const RED_LETTER_CUES =',
    literal,
    '',
  ].join('\n')
}
